# Daily update
name: updater

# Controls when the action will run
on:
  schedule:
    - cron:  '0 04 * * *'
  workflow_dispatch:
  
jobs: 
  plot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
            
    # Load repo and install R and pandoc
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1

    # Set-up R
    - name: Install packages
      run: |
        Rscript -e 'install.packages("ggplot2")'
        
    # Run R script
    - name: Make plot
      run: Rscript longevity.R

    # Add new files in data folder, commit along with other modified files, push
    - uses: stefanzweifel/git-auto-commit-action@v4.6.0
      with:
        commit_message: "daily update"